# Generated by Django 3.2.7 on 2022-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_seller',
            field=models.BooleanField(default=False, verbose_name='Top Seller'),
        ),
    ]
